import React from 'react';
import './ConditionAdviceModal.css';
import ReactMarkdown from 'react-markdown';


const ConditionAdviceModal = ({ isOpen, onClose, condition, advice, loading, error }) => {
    if (!isOpen) return null;

    return (
        <div className="modal-overlay" onClick={onClose}>
            <div className="modal-content" onClick={e => e.stopPropagation()}>
                <div className="modal-header">
                    <h2>Management Advice for {condition}</h2>
                    <button className="close-btn" onClick={onClose}>&times;</button>
                </div>

                <div className="modal-body">
                    {loading ? (
                        <div className="loading-spinner">
                            <div className="spinner"></div>
                            <p>Generating personalized medical advice from AI...</p>
                        </div>
                    ) : error ? (
                        <div className="error-message">
                            {error}
                        </div>
                    ) : (
                        <div className="advice-text">
                            <ReactMarkdown>{advice}</ReactMarkdown>
                        </div>
                    )}
                </div>

                <div className="modal-footer">
                    <p className="disclaimer">
                        <strong>Disclaimer:</strong> This advice is generated by AI and should not replace professional medical advice. Always consult with your doctor.
                    </p>
                    <button className="close-action-btn" onClick={onClose}>Close</button>
                </div>
            </div>
        </div>
    );
};

export default ConditionAdviceModal;
